### ISSUE TITLE
[945] User should not see jumps in scroll when ads are destroyed

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa#135]
If you scroll down in [this url](https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A25) to page 2 or 3, page 1 ads get destroyed. If the ad height is not equal to min-height, that add container is shrunk and the scroll jumps.

Maybe the ad containers should not be shrunk once they are made bigger than their `min-height` to prevent this behaviour.

For some reason, I can't reproduce it in Chrome, but it definitely happens in Safari.

Best way to reproduce it is scroll all the way down to end of page 3, then slowly scroll up to page 1/2.

This is a video the customer sent:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A26

---- 
https://frontity.pipedrive.com/deal/44
Pageviews: **(10M)**
Environment: **production (x6)**
Range: **medium (x3)**
Behaviour: **not-nice (x1)**
Mass: **everyone (x5)**
PRIORITY: **[900]**

https://frontity.pipedrive.com/deal/151
Pageviews: **(0.1M)**
Environment: **production (x10)**
Range: **medium (x3)**
Behaviour: **not-nice (x1)**
Mass: **everyone (x5)**
Referrer: **yes (x3)**
PRIORITY: **[45]**

**Comment by luisherranz** [comment]
@DAreRodz could you please take a look at this issue and let me know if my assumptions make sense?

**Comment by orballo** [comment]
This issue can't be totally fixed. The PR solution will prevent the scroll to jump on ads destruction by preserving the last height that the ad container had, but it can't prevent the scroll to jump when a new higher ad is created while scrolling back. For that the ads should have a fixed height, and that's not what the customer wants.

This issue only takes place in Safari, because Chrome prevents it adjusting the scroll position to conserve the current view when the body gets higher.
