### ISSUE TITLE
Design how to access all the HTML nodes from React

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa#75]
Child of https://github.com/frontity/frontity/issues/74

**Comment by luisherranz** [comment]
![aww-board (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58af0e4ea157412000799534/125516c66e82c728ace21e0d46e9838d6e808ca89dedff0bf514b2d86b56357c2301a03f32dfa17dbd1628525b584fa8410b5c41fff98929a0e46f74db095fffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98949c4ed3c21e78389493b0c48.png)

**Comment by DAreRodz** [comment]
### H2R design

* NPM package that exports a react **component** (`H2R`) and a mobx-state-tree **model**. That model is intented to be exposed by themes in their stores, and will contain actions to init H2R and manage processors.

* One type of processors (merge processors and converters).

* Themes will add their own processors using actions in the model. Other packages will do the same.

* `H2R` receives processors from the store using `mobx-react`'s `inject`.

* Change the processors API. Send `element`, `parent` and `htmlTree` as arguments. Send also `stores`, `item` (this one should come from a react prop) and `payload`.

* Asign priorities to processors using numbers (the less value the higher priority). Also let the possibility to use the strings `'high'`, `'medium'`, `'low'` with number equivalents (`10`, `20`, `30` respectively). Priorities mark the execution order of processors.

* Change the slot injector algorithm to be an ordinary processor (with `high` priority).

* Consider using the last version of **Himalaya AST Specification** ([ast-spec-v1](https://github.com/andrejewski/himalaya/blob/master/text/ast-spec-v1.md) instead of [ast-spec-v0](https://github.com/andrejewski/himalaya/blob/master/text/ast-spec-v0.md))

This is a preliminary version. Feel free to comment/suggest!

**Comment by luisherranz** [comment]
Two more things:

- Document the new API and how to use it in a theme or an extension.
- Make sure that if you don't pass test, all elements are sent to the processor.

**Comment by luisherranz** [comment]
List of latest decisions:

- [x] Add `filterAtributes` by default
- [x] Change `tagName` to `component`
- [x] Change `attributes` to `props`
- [x] Add `parent` to `element`
- [x] return should `shallowMerge`
- [ ] reevaluate priorities after completion

**Comment by DAreRodz** [comment]
I will continue working in H2R implementation in the repo that I've just created. Closing this issue and starting with https://github.com/frontity/frontity/issues/76.
