### ISSUE TITLE
Check DoubleClick ads

### ISSUE THREAD

**Issue by DAreRodz** [wp-pwa/wp-pwa#93]

**Comment by DAreRodz** [comment]
DoubleClick ads are working fine, though the implementation is improvable.

**Comment by DAreRodz** [comment]
Another issue has been open to improve it: https://github.com/wp-pwa/wp-pwa/issues/97

**Comment by luisherranz** [comment]
create-react-app v2 beta compiles `node_modules` using "new JavaScript features". New features could mean ES6-7 only or maybe a usage of `"jsnext:main": "index.js"`. We should take a look at what they're doing.

https://github.com/facebook/create-react-app/pull/3776

**Comment by luisherranz** [comment]
We need to be able to serve Frontity PWA assets from within WP. Yep, we'll lose the ability to do SSR.

It'd be easier if the setup doesn't involve programming, maybe using a shortcode in a page or something like that. The shortcode could be `[frontity]`.

Maybe it also needs a js code injected with `wp_head` to remove `<body>` and leave only a `<div class="root">` for React. It could:
- Show a splash screen.
- Create global variable for Frontity to consume, similar to what the injector is doing today.
- Set public path to `https://domain.com/wp-content/plugins/frontity/.build/client/static/`.
- Insert the webpack scripts (main, vendors...). We lose the ability to know which scripts are needed for that page before hand. <-- We need a way to know what scripts (with their hashes) are needed. Maybe a html file? Or a `?version=xxx` like WP? It'd be better if the build script doesn't need to change.

Frontity and the WP plugin will share the same folder. `.build` can't be in the .gitignore.

`<head>` could remaing untoched.

ReactDOM should do `render` instead of `hydrate`.

Once the PWA has loaded, the user must be able to navigate other pages using the PWA.

The shortcode could include options, like `[frontity mode="mobile,tablet"]`.

The WP plugin must include the Frontity assets, so they need to be built and included in the plugin files.

Maybe what Frontity needs to do, is to make it really simple to create WP plugins like this. Or WP themes.

Settings can be populated in WP and injected via the global variable `initialState`. MST can get them from there, as it usually does with SSR.

**Comment by luisherranz** [comment]
Or even better, we can generate `matches` without any restriction, then use them for settings:

```json
[
  {
    "site": "my-blog",
    "matches": {
      "amp_localhost": [
        "localhost:3000.+/amp/?$",
        "localhost:3000.+[?&}amp=true"
      ],
      "main_localhost": "localhost:3000",
      "amp": [
        "amp.my-blog.com",
        "my-blog.com.+/amp/?$",
        "my-blog.com.+[?&}amp=true"
      ],
      "main": "my-blog.com"
    },
    "settings": [
      {
        "matches": ["amp_localhost", "main_localhost"],
        "namespaces": "frontity",
        "data": {
          "publicPath": "https://localhost:3000"
        }
      },
      {
        "matches": ["amp", "main"],
        "namespaces": "frontity",
        "data": {
          "publicPath": "https://v1.frontity.io"
        }
      },
      {
        "matches": ["main", "main_localhost"],
        "namespaces": "frontity",
        "data": {
          "url": "https://my-blog.com"
        }
      },
      {
        "matches": ["amp", "amp_localhost"],
        "namespaces": "frontity",
        "data": {
          "url": "https://amp.my-blog.com"
        }
      }
    ],
    "packages": {
      "@frontity/saturn-theme": {
        "settings": [
          {
            "matches": "*",
            "namespaces": "theme",
            "data": {
              "color": "#AAA"
            }
          },
          {
            "matches": "*",
            "namespaces": "h2r",
            "data": {
              "removeWpEmbeds": true
            }
          }
        ]
      },
      "@frontity/analytics": {
        "settings": [
          {
            "matches": "main",
            "namespaces": "analytics",
            "data": {
              "analytics": "UA-001"
            }
          },
          {
            "matches": "amp",
            "namespaces": "analytics",
            "data": {
              "analytics": "UA-002"
            }
          }
        ]
      },
      "@frontity/wp-org-connection": {
        "settings": [
          {
            "matches": "*",
            "namespaces": "connection",
            "data": {
              "endpoint": "https://my-blog.com/wp-json/",
              "perPage": 13
            }
          }
        ]
      }
    }
  }
]
```

If `settings` is an array, it accepts `matches`, `namespaces` and `data`. Default `matches` is `"*"` and default namespace is all namespaces from the package.

The super simple version would be something like:
```json
  {
    "site": "my-blog",
    "settings": {
      "url": "https://my-blog.com"
    },
    "packages": {
      "@frontity/saturn-theme": {
        "settings": {
          "color": "#AAA"
        }
      },
      "@frontity/wp-org-connection": {
        "settings": {
          "endpoint": "https://my-blog.com/wp-json/",
          "perPage": 13
        }
      }
    }
  }
```

Which is the equivalent to: 
```json
[
  {
    "site": "my-blog",
    "matches": {
      "default": "*"
    },
    "settings": [
      {
        "matches": "default",
        "namespaces": "frontity",
        "data": {
          "url": "https://my-blog.com"
        }
      }
    ],
    "packages": {
      "@frontity/saturn-theme": {
        "settings": [
          {
            "matches": "default",
            "namespaces": "theme",
            "data": {
              "color": "#AAA"
            }
          }
        ]
      },
      "@frontity/wp-org-connection": {
        "settings": [
          {
            "matches": "default",
            "namespaces": "connection",
            "data": {
              "endpoint": "https://my-blog.com/wp-json/",
              "perPage": 13
            }
          }
        ]
      }
    }
  }
]
```

Namespaces are extracted from package namespaces.

If we don't want namespaces to be defined by the user in `settings.json` (so we can work without `package.json` file, they should be defined somehow by the package creator.
